name: Only in feature branches

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - development
          - staging
          - production

permissions:
  contents: read

jobs:
  show-env:
    name: Show Env if starts with feature
    if: startsWith(github.ref_name, 'feature')
    runs-on: self-hosted
    steps:
      - name: read environment
        run: |
          echo "Ich bin ein Feature-Branch"

  show-always:
    name: Show always
    runs-on: self-hosted
    steps:
      - name: read environment
        run: |
          echo "Ich bin immer da"

